# Generated by Django 5.0.3 on 2024-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('revenue', models.IntegerField()),
                ('employees', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=100)),
                ('fortune_100_rank', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
    ]
