# Generated by Django 5.0.3 on 2024-08-21 11:59

from django.db import migrations

# Migration of initial profile data
def load_initial_data(operation, data):
    from django.core.management import call_command
    call_command("loaddata", "top30initialdata")

class Migration(migrations.Migration):

    dependencies = [
        ('top30profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
